name: ".NET"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
      
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./Rich.HaoDanKu\Rich.HaoDanKu.csproj
        VERSION_FILE_PATH: ./common.props
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
